# Those hparams which are in a list 
# apply differently to each ntwrk
# Should match with NUM_AGENTS_PER_TYPE

"LR": [0.0002,0.0002]
"NUM_ENVS": 16384 #128
"NUM_STEPS": 64
"NUM_STEPS_EVAL" : 64
"GRU_HIDDEN_DIM": 128
"FC_DIM_SIZE": 128
"TOTAL_TIMESTEPS": 5e9 #5e8
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 16
"GAMMA": [0.99,0.99]
"GAE_LAMBDA": [0.99,0.99]
"CLIP_EPS": 0.2
"SCALE_CLIP_EPS": [False,False]
"ENT_COEF": [0.01,0.01]
"VF_COEF": [0.5, 0.5]
"MAX_GRAD_NORM": [0.5,0.5]
"ACTIVATION": ["relu","relu"]
"ENV_NAME": "JAXMARL-Lob-v0"
"NUM_AGENTS_PER_TYPE": [5,5]
"SEED": 2
"N_DEVICES": 4
"ENV_CONFIG": null
"ANNEAL_LR": [True,True]

# WandB Params
"ENTITY": "2670933993-"
"PROJECT": "PMAP_SPEED" #"DEBUG"
"WANDB_MODE" : "online"

# High-Level Params
"CALC_EVAL" : False
"TimePeriod" : "20120621"
"EvalTimePeriod" : "20120621"
"Calculate Baseline" : False
"Timing" : True

"world_config": {
  "alphatradePath": "/home/atomus/JaxMARL-HFT",
  "dataPath": "/home/atomus/JaxMARL-HFT/data",
  "stock": "AMZN",
  "timePeriod": "20120621",
  "day_start": 34200,
  "day_end": 57000,
  "tick_size": 100,
  "book_depth": 10
}



